## Hooks

# add line numbers
hook global WinCreate .* %{addhl number_lines}

# add brackets highlighting
hook global WinCreate .* %{addhl show_matching}

# soft tabs
set global indentwidth 4
set global tabstop     4
hook global BufSetOption filetype=(?!makefile).* %{
    hook buffer InsertChar \t %{ exec -draft h@ }
}

# scrolloff
set global scrolloff 12,12

# autowrap at 80 chars
hook global BufSetOption filetype=(?!tsv).* %{
    set global autowrap_column 80
    hook buffer WinCreate .* %{ autowrap-enable }
}

colorscheme default

# Markdown manipulation
# =====================

# copy paste to system clipboard
map global user y '<a-|>xsel --input --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'
