## Hooks

# add line numbers
hook global WinCreate .* %{addhl number_lines}

# add brackets highlighting
hook global WinCreate .* %{addhl show_matching}

# soft tabs
set global indentwidth 4
set global tabstop     4
hook global BufSetOption filetype=(?!makefile).* %{
    hook buffer InsertChar \t %{ exec -draft h@ }
}

# scrolloff
set global scrolloff 12,12

# autowrap at 80 chars
set global autowrap_column 80
hook global WinCreate .* %{ autowrap-enable }

colorscheme default

# Markdown manipulation
# =====================

# insert date as level 2 header
map global user d %{| date +\%F <ret>}

# compile latex
map global user l %{:%sh{alias_call md latex $kak_buffile}<ret>}
# compile beamer
map global user b %{:%sh{alias_call md beamer $kak_buffile}<ret>}

# format text with pandoc
map global user g %{ X | pandoc --from=markdown --to=markdown --columns=80 <ret> }

# custom commands
map global user h XypjXHr=A<ret><esc>
map global user j XypjXHr-A<ret><esc>XHd
map global user r %{ | pandoc-citeproc --bib2yaml --format=biblatex <ret> }

# copy paste to system clipboard
map global user y '<a-|>xsel --input --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'
