#!/usr/bin/env zsh

# location of lockscreen images
PICS="/home/alli/media/pics/lockscreens/"

# sort randomly, pick last file
# i3lock only takes pngs
RANDPIC=$(ls $PICS/*.png | shuf -n1)

i3lock -t -i $RANDPIC
